[package]
name = "calamine"
version = "0.29.0"
authors = ["Johann Tuffe <tafia973@gmail.com>", "Martin Bammer <bam5wi@bosch.com>"]
repository = "https://github.com/tafia/calamine"
documentation = "https://docs.rs/calamine"
description = "An Excel/OpenDocument Spreadsheets reader and deserializer in pure rust"
license = "MIT"
readme = "README.md"
keywords = ["excel", "ods", "xls", "xlsx", "xlsb"]
categories = ["encoding", "parsing", "text-processing"]
exclude = ["tests/**/*"]
edition = "2024"
rust-version = "1.85"

[dependencies]
atoi_simd = "0.16"
byteorder = "1.5"
codepage = "0.1"
encoding_rs = "0.8"
fast-float2 = "0.2"
log = "0.4"
serde = "1.0"
quick-xml = { version = "0.37.5", features = ["encoding"] }
zip = { version = "4.3", default-features = false, features = ["deflate"] }
chrono = { version = "0.4", features = [
    "serde",
], optional = true, default-features = false }

[dev-dependencies]
glob = "0.3"
env_logger = "0.11"
rstest = { version = "0.26.1", default-features = false }
serde_derive = "1.0"
sha2 = "0.10"

[features]
default = []
dates = ["chrono"]
picture = []

[package.metadata.docs.rs]
features = ["dates", "picture"]
